# remote_theme: pages-themes/tactile@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one


title: APCSA Java Game Design with Processing
description: Use this Java-Processing framework to make a game using skills learned from your APCSA course
# show_downloads: true
# google_analytics:
theme: jekyll-theme-tactile