archetypesdir = 'docs/archetypes'
assetdir = 'docs/assets'
contentdir = 'docs/content'
datadir = 'docs/data'
i18n = 'docs/i18n'
layoutdir = 'docs/layouts'
publishdir = 'docs/public'
resourcedir = 'docs/resources'
staticdir = 'docs/static'
themesdir = 'docs/themes'

baseURL = 'https://jabianchi.github.io/'
languageCode = 'en-us'
title = 'APCSA Java Game with Processing Project'
theme = 'ananke'